project:
  type: book
  output-dir: docs

book:
  title: "Scientific Writing and Communication"
  author: "Thiyanga S. Talagala"
  date: ""
  chapters:
    - index.qmd
    - part: part1.qmd
      chapters:
      - intro.qmd
      - chap2.qmd
      - chap3.qmd
      - chap4.qmd
    - part: part2.qmd
      chapters:
      - chap5.qmd
      - chap6.qmd
      - chap7.qmd
      - summary.qmd
      - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
jupyter: python3


